"""
pointers.py — generate ALL IDE-specific pointer files from a single template.

Each generated file is 10-20 lines. Each points to .ai-memory/CONTEXT.md.
Idempotent: safe to run multiple times (overwrites if ai-memory marker present,
skips if the file was not generated by ai-memory).

Generates:
  CLAUDE.md
  .cursorrules
  AGENTS.md
  .windsurfrules
  GEMINI.md
  .github/copilot-instructions.md
  .junie/guidelines.md
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")


# ── Pointer file targets ───────────────────────────────────────────────────────

# (relative_path, preamble_comment, description)
POINTER_TARGETS: list[tuple[str, str, str]] = [
    ("CLAUDE.md",                          "<!-- ai-memory pointer for Claude Code -->",      "Claude Code"),
    (".cursorrules",                        "<!-- ai-memory pointer for Cursor -->",           "Cursor"),
    ("AGENTS.md",                          "<!-- ai-memory pointer for Codex CLI -->",        "Codex CLI / OpenClaw"),
    (".windsurfrules",                     "<!-- ai-memory pointer for Windsurf -->",         "Windsurf"),
    ("GEMINI.md",                          "<!-- ai-memory pointer for Gemini CLI -->",       "Gemini CLI"),
    (".github/copilot-instructions.md",    "<!-- ai-memory pointer for VS Code Copilot -->", "VS Code + Copilot"),
    (".junie/guidelines.md",              "<!-- ai-memory pointer for JetBrains Junie -->",  "JetBrains + Junie"),
]

AI_MEMORY_MARKER = "<!-- ai-memory:"


def _load_template(template_path: Optional[Path] = None) -> str:
    """Load pointer.md.template, falling back to inline default."""
    if template_path and template_path.exists():
        return template_path.read_text(encoding="utf-8")

    # Inline fallback (matches templates/pointer.md.template)
    return """\
# Session directives
- Short sentences. 8-10 words max.
- No filler. No preamble. Tool-first.
- Read .ai-memory/CONTEXT.md before every task.
- Respect existing decisions. Reference by [date].
- Check blockers before suggesting workarounds.
- Follow .ai-memory/guidelines.md for coding standards.

# Project context
Read .ai-memory/CONTEXT.md for decisions, patterns, blockers, and recent activity.

# Skills (read the file when the topic comes up)
- Code review / PR / quality check → docs/01-sdlc/review.md
- Coding guidelines / standards / rules → docs/01-sdlc/guidelines.md
- Feature spec / requirement / planning → docs/01-sdlc/spec.md
- General help / how do I / show me → docs/01-sdlc/help.md
- New feature / implement / add → docs/01-sdlc/feature.md
- Bug / fix / error / failing → docs/01-sdlc/debug.md
- Onboard / new developer / getting started → docs/01-sdlc/onboard.md
- Sprint / summary / retro → docs/01-sdlc/sprint.md
"""


def _build_pointer_content(preamble: str, ide_name: str, template_body: str) -> str:
    return f"{AI_MEMORY_MARKER} generated for {ide_name} -->\n{preamble}\n\n{template_body.strip()}\n"


def _should_write(path: Path) -> bool:
    """
    Return True if we should write the pointer file.
    - File doesn't exist: yes
    - File exists with ai-memory marker: yes (overwrite our own file)
    - File exists without ai-memory marker: no (don't clobber user's file)
    """
    if not path.exists():
        return True
    content = path.read_text(encoding="utf-8", errors="ignore")
    return AI_MEMORY_MARKER in content


# ── Public API ─────────────────────────────────────────────────────────────────

def _matches_filter(ide_name: str, only: list[str]) -> bool:
    """Return True if ide_name matches any term in only (case-insensitive substring)."""
    lower = ide_name.lower()
    return any(term.lower() in lower for term in only)


def generate_pointers(
    repo_root: Path,
    template_path: Optional[Path] = None,
    verbose: bool = True,
    only: Optional[list[str]] = None,
) -> list[str]:
    """
    Generate IDE pointer files in repo_root.
    only: if provided, only write targets whose description matches any term.
    Returns list of relative paths that were written.
    """
    template_body = _load_template(template_path)
    written = []
    skipped = []

    targets = POINTER_TARGETS
    if only:
        targets = [t for t in POINTER_TARGETS if _matches_filter(t[2], only)]
        if verbose and not targets:
            names = ", ".join(t[2] for t in POINTER_TARGETS)
            print(f"  [!] no pointer targets matched {only}. Available: {names}")

    for rel_path, preamble, ide_name in targets:
        target = repo_root / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)

        if _should_write(target):
            content = _build_pointer_content(preamble, ide_name, template_body)
            target.write_text(content, encoding="utf-8")
            written.append(rel_path)
        else:
            skipped.append(rel_path)

    if verbose:
        for p in written:
            print(f"  ✓ wrote {p}")
        for p in skipped:
            print(f"  ~ skipped {p} (not generated by ai-memory)")

    return written


if __name__ == "__main__":
    import sys
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    # Try to find the template relative to this script
    script_dir = Path(__file__).parent.parent
    template = script_dir / "templates" / "pointer.md.template"
    generate_pointers(root, template_path=template)
